"""Added pending agreement column to mediation relation

Revision ID: 39e6d252c378
Revises: b5501368f9c3
Create Date: 2023-09-08 13:25:19.301547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e6d252c378'
down_revision = 'b5501368f9c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_agreement', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediation', schema=None) as batch_op:
        batch_op.drop_column('pending_agreement')

    # ### end Alembic commands ###
