"""created Booleans for commit statements

Revision ID: 5c2669193fc4
Revises: 
Create Date: 2023-09-01 13:39:58.240914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2669193fc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initiator_statement_committed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('other_statement_committed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediation', schema=None) as batch_op:
        batch_op.drop_column('other_statement_committed')
        batch_op.drop_column('initiator_statement_committed')

    # ### end Alembic commands ###
