"""set commitment to not nullable

Revision ID: b5501368f9c3
Revises: 5c2669193fc4
Create Date: 2023-09-01 13:50:57.585970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5501368f9c3'
down_revision = '5c2669193fc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_mediation')
    with op.batch_alter_table('mediation', schema=None) as batch_op:
        batch_op.alter_column('initiator_statement_committed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('other_statement_committed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediation', schema=None) as batch_op:
        batch_op.alter_column('other_statement_committed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('initiator_statement_committed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    op.create_table('_alembic_tmp_mediation',
    sa.Column('mediation_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('initiator_id', sa.INTEGER(), nullable=False),
    sa.Column('other_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp_started', sa.DATETIME(), nullable=True),
    sa.Column('initiator_conflict_statement', sa.TEXT(), nullable=True),
    sa.Column('other_conflict_statement', sa.TEXT(), nullable=True),
    sa.Column('initiator_statement_committed', sa.BOOLEAN(), nullable=False),
    sa.Column('other_statement_committed', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['initiator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['other_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('mediation_id')
    )
    # ### end Alembic commands ###
