"""removed pending agreement logicg from mediation

Revision ID: dc8e0f5c5338
Revises: e199b4561dbb
Create Date: 2023-09-08 16:43:34.788001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8e0f5c5338'
down_revision = 'e199b4561dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediation', schema=None) as batch_op:
        batch_op.drop_column('initiator_agreed')
        batch_op.drop_column('other_agreed')
        batch_op.drop_column('pending_agreement')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_agreement', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('other_agreed', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('initiator_agreed', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
