"""Added columns if users agreed to current agreement

Revision ID: e199b4561dbb
Revises: 39e6d252c378
Create Date: 2023-09-08 14:07:18.365976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e199b4561dbb'
down_revision = '39e6d252c378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initiator_agreed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('other_agreed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediation', schema=None) as batch_op:
        batch_op.drop_column('other_agreed')
        batch_op.drop_column('initiator_agreed')

    # ### end Alembic commands ###
